backend:
  name: git-gateway
  branch: develop

publish_mode: editorial_workflow

site_url: https://hajoeun.blog
media_folder: static/images
public_folder: /images
show_preview_links: true

collections:
  - name: "post"
    label: "Post"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    media_folder: "{{series}}/images"
    public_folder: ""
    preview_path: preview/{{slug}}
    path: "{{series}}/{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss" }
      - { label: "Description", name: "description", widget: "string"}
      - { label: "Series", name: "series", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
