backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts"
    create: true
    slug: "{{series}}-{{number}}"
    media_folder: "{{series}}/images"
    public_folder: ""
    path: "{{series}}/{{series}}-{{number}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss" }
      - { label: "Description", name: "description", widget: "string"}
      - { label: "Series", name: "series", widget: "string" }
      - { label: "Number", name: "number", widget: "number", value_type: "int" }
      - { label: "Body", name: "body", widget: "markdown" }
