backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

site_url: https://hajoeun.blog
media_folder: static/images
public_folder: /images
show_preview_links: true

collections:
  - name: "post"
    label: "Post"
    folder: "content/posts"
    create: true
    slug: "{{title}}"
    media_folder: "{{series}}/images"
    public_folder: ""
    preview_path: preview/{{slug}}
    path: "{{series}}/{{title}}"
    editor:
      preview: true
    fields:
      - {
        label: "Series",
        name: "series",
        widget: "select",
        options: [
          { label: "클린 코드", value: "clean-code" },
          { label: "Deno", value: "learn-deno" },
        ]
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss" }
      - { label: "Body", name: "body", widget: "markdown" }
